package gtranslator.ui;

public class Constants {
	public final static String PROPERTY_CHANGE_ACTIVITY_CLIPBOARD = "PROPERTY_CHANGE_ACTIVITY_CLIPBOARD";
	public final static String PROPERTY_CHANGE_MODE_CLIPBOARD = "PROPERTY_CHANGE_MODE_CLIPBOARD";
	public final static String PROPERTY_CHANGE_COOKIE = "PROPERTY_CHANGE_COOKIE";
	public final static String PROPERTY_CHANGE_DICTIONARY_DIR = "PROPERTY_CHANGE_DICTIONARY_DIR";
	public final static String PROPERTY_CHANGE_HISTORY = "PROPERTY_CHANGE_HISTORY";
	public final static String PROPERTY_CHANGE_SOUND = "PROPERTY_CHANGE_SOUND";
	public final static String PROPERTY_CHANGE_STATISTIC = "PROPERTY_CHANGE_STATISTIC";
	public final static String PROPERTY_CHANGE_DICTIONARY_PRONUNCIATION = "PROPERTY_CHANGE_DICTIONARY_PRONUNCIATION";
	public final static String PROPERTY_CHANGE_DICTIONARY_RESULT_DIR = "PROPERTY_CHANGE_DICTIONARY_RESULT_DIR";
	public final static String PROPERTY_CHANGE_DICTIONARY_BLOCK_LIMIT = "PROPERTY_CHANGE_DICTIONARY_BLOCK_LIMIT";
}
