package gtranslator.ui;

public class Constants {
	public final static String PROPERTY_CHANGE_ACTIVITY_CLIPBOARD_SETUP = "PROPERTY_CHANGE_ACTIVITY_CLIPBOARD_SETUP";
	public final static String PROPERTY_CHANGE_MODE_CLIPBOARD_SETUP = "PROPERTY_CHANGE_MODE_CLIPBOARD_SETUP";
	public final static String PROPERTY_CHANGE_ACTIVITY_CLIPBOARD_TRANS = "PROPERTY_CHANGE_ACTIVITY_CLIPBOARD_TRANS";
	public final static String PROPERTY_CHANGE_MODE_CLIPBOARD_TRANS = "PROPERTY_CHANGE_MODE_CLIPBOARD_TRANS";
	public final static String PROPERTY_CHANGE_INIT_CLIPBOARD_SETUP = "PROPERTY_CHANGE_INIT_CLIPBOARD_SETUP";
	public final static String PROPERTY_CHANGE_INIT_COOKIE_SETUP = "PROPERTY_CHANGE_INIT_COOKIE_SETUP";
	public final static String PROPERTY_CHANGE_INIT_DICTIONARY_DIR_SETUP = "PROPERTY_CHANGE_INIT_DICTIONARY_DIR_SETUP";
	public final static String PROPERTY_CHANGE_INIT_HISTORY_SETUP = "PROPERTY_CHANGE_INIT_HISTORY_SETUP";
	public final static String PROPERTY_CHANGE_INIT_SOUND_SETUP = "PROPERTY_CHANGE_INIT_SOUND_SETUP";
	public final static String PROPERTY_CHANGE_INIT_STATISTIC_SETUP = "PROPERTY_CHANGE_INIT_STATISTIC_SETUP";
}
